// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package zeromq.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import zeromq.custom.ZMQForwarderProxyHelper;
import zeromq.proxies.constants.Constants;

/**
 * Shutdown ZeroMQ forwarder proxy.
 */
public class ShutdownZeroMQForwarderProxy extends CustomJavaAction<java.lang.Void>
{
	public ShutdownZeroMQForwarderProxy(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		if(Constants.getForwarderProxyEnabled())
			ZMQForwarderProxyHelper.getInstance().shutDown();

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShutdownZeroMQForwarderProxy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
